export const cardData = [
    {
        Link: "/assest/s1.jpg",
        tag: "Just In",
        heading: "Nike Air Force 1 Mid '07",
        description: "Men's Shoes",
        color: "1",
        price: "MRP : ₹ 10,795.00",
    },
    {
        Link: "/assest/s2.jpg",
        tag: "Just In",
        heading: "Nike Court Vision Low Next Nature",
        description: "Men's Shoes",
        color: "1",
        price: "MRP : ₹ 4,695.00",
    },
    {
        Link: "/assest/s3.jpg",
        tag: "Just In",
        heading: "Nike Air Force 1 PLT.AF.ORM",
        description: "Women's Shoes",
        color: "1",
        price: "MRP : ₹ 10,295.00",
    },
    {
        Link: "/assest/s4.jpg",
        tag: "Just In",
        heading: "Nike Air Force 1 React",
        description: "Men's Shoes",
        color: "1",
        price: "MRP : ₹ 12,295.00",
    },
    {
        Link: "/assest/s5.jpg",
        tag: "Promo Exclusive",
        heading: "Air Jordan 1 Elevate Low",
        description: "Women's Shoes",
        color: "1",
        price: "MRP : ₹ 11,895.00",
    },
    {
        Link: "/assest/s6.jpg",
        tag: "Just In",
        heading: "Nike Standard Issue",
        description: "Men's Basketball Jersey",
        color: "1",
        price: "MRP : ₹ 3,595.00",
    },
    {
        Link: "/assest/s7.jpg",
        tag: "Promo Exclusive",
        heading: "Nike Dunk Low Retro SE",
        description: "Men's Shoes",
        color: "1",
        price: "MRP : ₹ 10,895.00",
    },
    {
        Link: "/assest/s8.jpg",
        tag: "Just In",
        heading: "Nike Dri-FIT Victory",
        description: "Men's Polo",
        color: "1",
        price: "MRP : ₹ 4,295.00",
    },
    {
        Link: "/assest/s9.jpg",
        tag: "Just In",
        heading: "Nike Court Vision Low",
        description: "Women's Shoes",
        color: "1",
        price: "MRP : ₹ 5,695.00",
    },
    {
        Link: "/assest/s10.jpg",
        tag: "Just In",
        heading: "Nike Air Max Pulse",
        description: "Men's Shoes",
        color: "1",
        price: "MRP : ₹ 12,995.00",
    },
    {
        Link: "/assest/s11.jpg",
        tag: "Just In",
        heading: "Nike Air Max SC",
        description: "Women's Shoes",
        color: "1",
        price: "MRP : ₹ 5,995.00",
    },
    {
        Link: "/assest/s12.jpg",
        tag: "Just In",
        heading: "Nike Dri-FIT UV",
        description: "Men's Shirt",
        color: "1",
        price: "MRP : ₹ 2,895.00",
    },
    {
        Link: "/assest/s13.jpg",
        tag: "Just In",
        heading: "Nike Air Max 90",
        description: "Men's Shoes",
        color: "1",
        price: "MRP : ₹ 11,695.00",
    },
    {
        Link: "/assest/s14.jpg",
        tag: "Just In",
        heading: "Nike Court Legacy Lift",
        description: "Women's Shoes",
        color: "1",
        price: "MRP : ₹ 7,695.00",
    },
    {
        Link: "/assest/s15.jpg",
        tag: "Just In",
        heading: "Nike Dri-FIT Tank",
        description: "Men's Training Tank",
        color: "1",
        price: "MRP : ₹ 1,995.00",
    },
    {
        Link: "/assest/s16.jpg",
        tag: "Just In",
        heading: "Nike Dri-FIT UV",
        description: "Men's Shorts",
        color: "1",
        price: "MRP : ₹ 3,295.00",
    },
    {
        Link: "/assest/s17.jpg",
        tag: "Just In",
        heading: "Nike Air Zoom Pegasus",
        description: "Running Shoes",
        color: "1",
        price: "MRP : ₹ 12,595.00",
    },
    {
        Link: "/assest/s18.jpg",
        tag: "Just In",
        heading: "Nike Blazer Low '77 Jumbo",
        description: "Women's Shoes",
        color: "1",
        price: "MRP : ₹ 8,595.00",
    },
    {
        Link: "/assest/s19.jpg",
        tag: "Just In",
        heading: "Nike Zoom Janoski OG",
        description: "Men's Skate Shoes",
        color: "1",
        price: "MRP : ₹ 6,595.00",
    },
    {
        Link: "/assest/s20.jpg",
        tag: "Just In",
        heading: "Jordan Stay Loyal 2",
        description: "Men's Shoes",
        color: "1",
        price: "MRP : ₹ 11,895.00",
    },
    {
        Link: "/assest/s21.jpg",
        tag: "Just In",
        heading: "Nike Blazer Low Platform",
        description: "Women's Shoes",
        color: "1",
        price: "MRP : ₹ 6,595.00",
    },
    {
        Link: "/assest/s22.jpg",
        tag: "Just In",
        heading: "Nike Sportswear",
        description: "Women's Fleece Shorts",
        color: "1",
        price: "MRP : ₹ 2,695.00",
    },
    {
        Link: "/assest/s23.jpg",
        tag: "Just In",
        heading: "Nike Dri-FIT UV Challenger",
        description: "Men's Running Shorts",
        color: "1",
        price: "MRP : ₹ 2,495.00",
    },
    {
        Link: "/assest/s24.jpg",
        tag: "Just In",
        heading: "Nike Dunk Low Retro",
        description: "Men's Shoes",
        color: "1",
        price: "MRP : ₹ 10,995.00",
    },
    {
        Link: "/assest/s25.jpg",
        tag: "Just In",
        heading: "Nike Air Max System",
        description: "Men's Shoes",
        color: "1",
        price: "MRP : ₹ 6,595.00",
    },
    {
        Link: "/assest/s26.jpg",
        tag: "Just In",
        heading: "Nike Dri-FIT Tee",
        description: "Women's Tee",
        color: "1",
        price: "MRP : ₹ 1,795.00",
    },
    {
        Link: "/assest/s27.jpg",
        tag: "Just In",
        heading: "Nike Air Force 1 '07",
        description: "Men's Shoes",
        color: "1",
        price: "MRP : ₹ 9,995.00",
    },
    {
        Link: "/assest/s28.jpg",
        tag: "Just In",
        heading: "Nike Court Vision Low",
        description: "Men's Shoes",
        color: "1",
        price: "MRP : ₹ 5,995.00",
    },
    {
        Link: "/assest/s29.jpg",
        tag: "Just In",
        heading: "Nike React Vision",
        description: "Men's Shoes",
        color: "1",
        price: "MRP : ₹ 12,995.00",
    },
    {
        Link: "/assest/s30.jpg",
        tag: "Just In",
        heading: "Nike Air Zoom Structure 24",
        description: "Men's Running Shoes",
        color: "1",
        price: "MRP : ₹ 10,695.00",
    },
];
